'use client';

import { useState } from 'react';
import { Container } from '@/components/ui/Container';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Save, X, Image as ImageIcon, Loader2, Check, ArrowLeft, Wand2 } from 'lucide-react';
import Link from 'next/link';
import api from '@/lib/axios';
import { useRouter } from 'next/navigation';

export default function NewProductPage() {
    const router = useRouter();
    const [isLoading, setIsLoading] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);

    const [formData, setFormData] = useState({
        name: '',
        sku: '',
        price: '',
        status: 'active',
        shortDescription: '',
        description: '',
        material: 'Platinum',
        categoryIds: []
    });

    const materials = ["Platinum", "18k Gold", "14k Gold", "Rose Gold", "Sterling Silver"];

    const handleMagicGenerate = async () => {
        if (!formData.name) {
            alert('Please enter a product name first.');
            return;
        }

        setIsGenerating(true);
        try {
            const response = await api.post('/ai/generate-content', {
                productName: formData.name,
                material: formData.material
            });

            if (response.data.success) {
                setFormData(prev => ({
                    ...prev,
                    description: response.data.description,
                    shortDescription: `A premium ${formData.material} ${formData.name}. Generated by Kusturiss AI.`
                }));
            }
        } catch (err) {
            console.error('Magic generation failed:', err);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);
        try {
            await api.post('/products', {
                ...formData,
                price: parseFloat(formData.price),
                dimensions: { length: 0, width: 0, height: 0 } // Mocked dimensions
            });
            router.push('/admin/products');
        } catch (err) {
            console.error('Product creation failed:', err);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="space-y-12 pb-24">
            {/* Header */}
            <div className="flex justify-between items-center">
                <div className="flex items-center space-x-6">
                    <Link href="/admin/products" className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                        <ArrowLeft size={20} />
                    </Link>
                    <h2 className="text-3xl font-heading italic">Curate New Piece</h2>
                </div>
            </div>

            <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                {/* Left Column: Essential Data */}
                <div className="lg:col-span-8 space-y-12">
                    <div className="bg-white p-10 shadow-sm border border-gray-100 space-y-10">
                        <div className="space-y-2">
                            <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Piece Name</label>
                            <input
                                required
                                value={formData.name}
                                onChange={e => setFormData({ ...formData, name: e.target.value })}
                                className="w-full text-2xl font-heading italic border-b border-gray-100 py-3 outline-none focus:border-secondary transition-colors"
                                placeholder="e.g. The Ethereal Solitaire"
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-8">
                            <div className="space-y-2">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Unique SKU</label>
                                <input
                                    required
                                    value={formData.sku}
                                    onChange={e => setFormData({ ...formData, sku: e.target.value })}
                                    className="w-full border-b border-gray-100 py-2 text-sm outline-none focus:border-secondary transition-colors"
                                    placeholder="KS-RING-001"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Primary Material</label>
                                <select
                                    value={formData.material}
                                    onChange={e => setFormData({ ...formData, material: e.target.value })}
                                    className="w-full border-b border-gray-100 py-2 text-sm outline-none focus:border-secondary bg-transparent transition-colors"
                                >
                                    {materials.map(m => <option key={m} value={m}>{m}</option>)}
                                </select>
                            </div>
                        </div>

                        <div className="space-y-6">
                            <div className="flex justify-between items-center">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Legacy Description</label>
                                <button
                                    type="button"
                                    onClick={handleMagicGenerate}
                                    disabled={isGenerating}
                                    className="flex items-center space-x-2 text-[10px] font-black uppercase tracking-widest text-secondary hover:text-primary transition-colors hover:scale-105 transform origin-right"
                                >
                                    {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                                    <span>AI Magic Enhance</span>
                                </button>
                            </div>
                            <textarea
                                required
                                value={formData.description}
                                onChange={e => setFormData({ ...formData, description: e.target.value })}
                                rows={8}
                                className="w-full border border-gray-100 p-6 text-sm italic leading-relaxed focus:border-secondary outline-none transition-colors bg-gray-50/30"
                                placeholder="Write the story of this piece..."
                            />
                        </div>
                    </div>
                </div>

                {/* Right Column: Pricing & Meta */}
                <div className="lg:col-span-4 space-y-8">
                    <div className="bg-white p-8 shadow-sm border border-gray-100 space-y-8">
                        <div className="space-y-2">
                            <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">MSRP ($)</label>
                            <input
                                required
                                type="number"
                                value={formData.price}
                                onChange={e => setFormData({ ...formData, price: e.target.value })}
                                className="w-full text-3xl font-medium tracking-tight border-b border-gray-100 py-2 outline-none focus:border-secondary transition-colors"
                                placeholder="0.00"
                            />
                        </div>

                        <div className="space-y-4">
                            <label className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Product Status</label>
                            <div className="flex space-x-2">
                                {['active', 'draft'].map(s => (
                                    <button
                                        key={s}
                                        type="button"
                                        onClick={() => setFormData({ ...formData, status: s })}
                                        className={`flex-1 py-3 text-[10px] font-bold uppercase tracking-widest border transition-all ${formData.status === s ? 'bg-primary text-white border-primary' : 'bg-white text-gray-400 border-gray-100 hover:border-gray-300'
                                            }`}
                                    >
                                        {s}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="pt-8 border-t border-gray-50">
                            <button
                                type="submit"
                                disabled={isLoading}
                                className="w-full bg-secondary text-primary py-5 text-[10px] font-bold uppercase tracking-[0.2em] hover:bg-primary hover:text-white transition-all flex items-center justify-center space-x-3 shadow-lg transform active:scale-95"
                            >
                                {isLoading ? <Loader2 className="animate-spin" size={18} /> : (
                                    <>
                                        <Save size={18} />
                                        <span>Commit to Inventory</span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>

                    {/* AI Preview Card */}
                    <AnimatePresence>
                        {formData.name && (
                            <motion.div
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                className="bg-primary p-8 text-white relative overflow-hidden"
                            >
                                <div className="absolute -top-4 -right-4 opacity-10">
                                    <ImageIcon size={120} />
                                </div>
                                <h4 className="text-[10px] font-bold uppercase tracking-[0.3em] mb-6 opacity-60">Visual Mockup Prompt</h4>
                                <p className="text-xs italic leading-relaxed mb-8">
                                    "High-end professional studio photography of {formData.name} made of {formData.material}. Macro lens focus, luxurious velvet background."
                                </p>
                                <div className="flex items-center space-x-2 text-[10px] font-bold uppercase tracking-widest text-secondary">
                                    <Wand2 size={12} />
                                    <span>AI Ready for Generation</span>
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </form>
        </div>
    );
}
